Utalca/Utalca/Models/Alumno.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Utalca.Models
{
    public class Alumno
    {
        public string Nombre { get; set; }
        public string Biografia { get; set; }
        public Alumno()
        {
            Biografia = "Sabio y sofisticado de gran fuerza y lealtad. También era un habilidoso mecánico. Chewbacca, como muchos wookiees, podía entender básico, pero no podía hablarlo debido a la estructura vocal de su especie. En vez de eso él hablaba en shyriiwook, el idioma wookiee principal, compuesto en su gran mayoría de gruñidos, a sus compañeros que no eran wookies, que normalmente hablaban básico. ";
        }

       
    }
}

Utalca/Utalca/Models/Asistencia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Utalca.Models
{
    public class Asistencia
    {
        public long IDParticipante { get; set; }
        public long IDCurso { get; set; }
        public long fechaClase { get; set; }
    }
}

Utalca/Utalca/Models/Profesor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Utalca.Models
{
    public class Profesor
    {
        private int edad = 0;

        public Profesor()
        {
            this.FechaNacimiento = new DateTime(1985, 5, 26);
        }

        public long ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Biografia { get; set; }
        public string SitioWeb { get; set; }
        public string Rol { get; set; }
        public string Foto { get; set; }
        public DateTime FechaNacimiento { get; private set; }
        public ControlAsistencia.Curso[] Cursos{ get; set; }
    public int Edad
        {
            get
            {
                this.edad = Convert.ToInt32((DateTime.Now - this.FechaNacimiento).TotalDays / 365);
                return this.edad;
            }

        }


    }
}

Utalca/Utalca/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Utalca.Controllers
{
    public class AlumnoController : Controller
    {
        
       
        public ActionResult Detalles(string nombre)
        {
            var alumno = new Models.Alumno();
            alumno.Nombre = nombre;
            return View(alumno);
        }
    }
}

Utalca/Utalca/Controllers/CursoApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Utalca.Controllers
{
    public class CursoApiController : ApiController
    {
        // GET api/<controller>
        public bool Get(Utalca.Models.Asistencia value)
        {
            var servicio = new ControlAsistencia.ControlAsistenciaClient();
            return servicio.RegistrarAsistencia(value.IDParticipante, value.IDCurso, value.fechaClase);           
        }

        // GET api/<controller>/5
        public Utalca.ControlAsistencia.Curso Get(int id)
        {
            var servicio = new ControlAsistencia.ControlAsistenciaClient();
            var curso = servicio.Curso(id);
            return curso;
        }

        // POST api/<controller>
        public void Post([FromBody]Utalca.Models.Asistencia value)
        {
            var servicio = new ControlAsistencia.ControlAsistenciaClient();
            servicio.RegistrarAsistencia(value.IDParticipante,value.IDCurso,value.fechaClase);
        }

        // PUT api/<controller>/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/<controller>/5
        public void Delete(int id)
        {
        }
    }
}

Utalca/Utalca/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Utalca.Controllers
{
    public class CursoController : Controller
    {
        // GET: Curso
        public ActionResult Index()
        {
            var servicio = new ControlAsistencia.ControlAsistenciaClient();
            var cursos = servicio.Cursos();
            return View(cursos);
        }

        public ActionResult Detalles(long id)
        {
            var servicio = new ControlAsistencia.ControlAsistenciaClient();
            var curso = servicio.Curso(id);
            return View(curso);
        }
    }
}

Utalca/Utalca/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Utalca.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Utalca/Utalca/Controllers/ProfesorApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Utalca.Controllers
{
    public class ProfesorApiController : ApiController
    {
        // GET: api/ProfesorApi
        public IEnumerable<Models.Profesor> Get()
        {
            
           return Servicio.DatosProfesor.Profesores();
        }

        // GET: api/ProfesorApi/5
        public string Get(int id)
        {
            var servicio = new ControlAsistencia.ControlAsistenciaClient();
            var curso = servicio.CursosPorProfesor(id);
            return "value";
        }

        // POST: api/ProfesorApi
        public void Post([FromBody]string value)
        {
            var var = 0;
        }

        // PUT: api/ProfesorApi/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/ProfesorApi/5
        public void Delete(int id)
        {
        }
    }
}

Utalca/Utalca/Controllers/ProfesorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Utalca.Controllers
{
    public class ProfesorController : Controller
    {
        // GET: Profesor
        public ActionResult Index()
        {
            var profesores = Servicio.DatosProfesor.Profesores();
            return View(profesores);
        }


        public ActionResult Detalles(long id)
        {
            var servicio = new ControlAsistencia.ControlAsistenciaClient();
            var profesores = Servicio.DatosProfesor.Profesores();
            var profesor = profesores[0];
            if (id%2==0)
            {
                profesor = profesores[0];
            }
            else if(id % 3 == 0)
            {
                profesor = profesores[1];
            }
            else if (id % 5 == 0)
            {
                profesor = profesores[2];
            }
            else
            {
                profesor = profesores[3];
            }
            profesor.Cursos = servicio.CursosPorProfesor(id);
            if (profesor != null)
            {
                return View("Detalles", profesor);
            }
            else
            {
                return View("ProfesorNoEncontrado", "Profesor");
            }
        }

        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(Models.Profesor p)
        {
            var profesores = Servicio.DatosProfesor.Profesores();
            if(profesores.Any(m => m.Nombre == p.Nombre))
            {
                Utils.MensajesUI.SetError("Ya existe un usuario con ese nombre");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Servicio.DatosProfesor.Profesores().Add(p);
                return RedirectToAction("Index", "Profesor");
            }
            
        }
    }
}

Utalca/Utalca/Views/Alumno/Detalles.cshtml
@model Utalca.Models.Alumno
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Estudiante - Facultad Ingeniería";
}


<div class="row">
    <div class="col-md-3">
        <div class="gallery-box">
            <img style="width: 200px;" src="/Content/img/Chewbacca.png" />
        </div>
        <h4 id="nombre" hidden="true"class="card-title">@Model.Nombre </h4>
        <hr style="clear:both" />
    </div>
    <div class="col-md-9 ">
        <div class="panel panel-default" style="background-color:#f9f9f9">
            <div class="panel-body">
                <h3>Biografía</h3>
                <hr style="clear:both" />
                <p>@Model.Biografia</p>

            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var nombre = $('#nombre').text();
        var titulo = $('#titulo').text(nombre);
    });
</script>

Utalca/Utalca/Views/Alumno/Index.cshtml
@model IEnumerable<Utalca.Models.Alumno>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Estudiante - Facultad Ingeniería";
}


<div class="row">
    <div class="col-md-3">
        <div class="gallery-box">
            <img style="width: 200px;" src="/Content/img/Chewbacca.png" />
        </div>
        <h4 id="nombre" hidden="true" class="card-title">@Model.Nombre </h4>
        <hr style="clear:both" />
        

    </div>
    <div class="col-md-9 ">
        <div class="panel panel-default" style="background-color:#f9f9f9">
            <div class="panel-body">
                <h3>Biografía</h3>
                <hr style="clear:both" />
                <p>@Model.Biografia</p>

            </div>
        </div>
    </div>
</div>
<script>
        $(document).ready(function () {
            var titulo = $('#titulo').text("Académicos");
            console.log(titulo);
        });
</script>

Utalca/Utalca/Views/Curso/Detalles.cshtml
@model Utalca.ControlAsistencia.Curso
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Detalles Curso";
}
<h2 id="nombre" hidden="true">@Html.DisplayFor(model => model.Nombre)</h2>
<div class="row">
    <div class="col-md-3">
        <p><strong>Profesores</strong></p>
        @foreach (var participante in Model.Profesores)
        {
            <p><a  href="@Url.Action("Detalles", "Profesor", new { id =participante.ID })" >@participante.Nombre</a></p>
        }
        <p><strong>Carrera</strong> </p>
        <p>@Model.Carrera.Nombre</p>
        <p><strong>Creditos</strong> </p>
        <p>@Model.Creditos</p>
        <p><strong>Plan</strong> </p>
        <p>@Model.Plan.Nombre</p>
        <p><strong>Sección</strong> </p>
        <p>@Model.Seccion</p>
        <p><strong>Alumnos</strong> </p>
        @foreach (var participante in Model.Alumnos)
        {
            <p><a href="@Url.Action("Detalles", "Alumno", new { nombre = participante.Nombre })">@participante.Nombre</a></p>
        }
        <p><strong>Ayudantes</strong> </p>
        @foreach (var participante in Model.Ayudantes)
        {
            <p><a href="@Url.Action("Detalles", "Alumno", new { nombre = participante.Nombre })">@participante.Nombre</a></p>
        }
    </div>
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h5>Registrar Asistencia</h5>
            </div>
            <div class="panel-body" style="overflow:auto; height:400px;">
                @foreach (var clase in Model.Horario)
                {
                    <div class="panel-group">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" href="#collapse1_@clase.Fecha.ToString("yyyyMMddHHmm")">
                                        @Html.DisplayFor(modelItem => clase.Titulo)
                                    </a>
                                    <a data-toggle="collapse" id="clase @clase.Fecha" href="#collapse1_@clase.Fecha.ToString("yyyyMMddHHmm")" class="pull-right">
                                        @Html.DisplayFor(modelItem => clase.Fecha)
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse1_@clase.Fecha.ToString("yyyyMMddHHmm")" class="panel-collapse collapse">
                                <ul class="list-group">
                                    @foreach (var participantes in clase.Presentes)
                                    {
                                        <li class="list-group-item">
                                            @Html.DisplayFor(modelItem => participantes.Nombre)
                                            <input id="idAsistencia @participantes.ID @clase.Fecha" type="checkbox" class="pull-right">
                                        </li>
                                    }
                                </ul>
                                <div class="panel-footer">@Html.DisplayFor(modelItem => clase.Sala.Nombre)</div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<br />
<p>
    @Html.ActionLink("Volver a Cursos", "Index")
</p>
<script>
    var nombre = $('#nombre').text();
    $('#titulo').text(nombre);
    $("input[id^='idAsistencia']").on("click", function () {
        var idParticipante = $(this).attr("id").split(" ")[1];
        var fecha = $(this).attr("id").split(" ")[2];
        idParticipante = parseInt(idParticipante);

        console.log(idParticipante);
        console.log(fecha);
        $.ajax({
            url: "/api/CursoApi",
            data: { IDParticipante: idParticipante, IDCurso: @Model.ID, FechaClase: fecha},
            accepts: "application/json",
            contentType: "application/x-www-form-urlencoded; charset=UTF-8",
            method: "POST",
            success: function (result) {
                
            }
        }).fail(function (e) {
            
        });
      }
    );
</script>

Utalca/Utalca/Views/Curso/Index.cshtml
@model IEnumerable<Utalca.ControlAsistencia.Curso>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Cursos - Facultad Ingeniería";
}



<div class="row">
    <div class="col-md-9">
        @foreach (var item in Model)
        {
            <div class="col-md-6">
                <div class="thumbnail">
                    <img src="/Content/img/imgNoDisponible.png" alt="logo" style="height: 200px;">
                    <div class="caption">
                        <h4>@Html.DisplayFor(modelItem => item.Nombre)</h4>
                        <ul class="list-inline">
                            <li>
                                @foreach (var p in item.Profesores)
                                {
                                    <i class="fa fa-user" style="color: gray;"></i>
                                    <a href="@Url.Action("Detalles", "Profesor", new { id = p.ID })" style="color: gray;">@Html.DisplayFor(modelItem => p.Nombre)</a>
                                    <br />
                                }
                            </li>
                            <li>
                                <i class="fa fa-group" style="color: gray;"></i>
                                <a href="#" style="color: gray;">@item.Alumnos.Length</a>
                            </li>  
                            <li>
                                <i class="fa fa-sitemap" style="color: gray;"></i>
                                <a href="#" style="color: gray;">@Html.DisplayFor(modelItem => item.Seccion)</a>
                            </li>
                            <li>
                                <i class="fa fa-credit-card" style="color: gray;"></i>
                                <a href="#" style="color: gray;">@Html.DisplayFor(modelItem => item.Creditos)</a>
                            </li>
                            <li>
                                <i class="fa fa-graduation-cap" style="color: gray;"></i>
                                <a href="#" style="color: gray;">@Html.DisplayFor(modelItem => item.Plan.Nombre)</a>
                            </li>                      
                        </ul>
                        <a href="@Url.Action("Detalles", "Curso", new { id = item.ID })" class="btn btn-primary" role="button">Detalles</a>
                    </div>
                </div>
                <br />
                <br />
            </div>
        }
    </div>
    <div class="col-md-3">
        <h3><i class="fa fa-university"></i>  Carreras</h3>
        @foreach (var item in Model)
        {
            <ul class="list-unstyled">
                <li>
                    <i class="fa fa-angle-right" style="color:dodgerblue;"></i>
                    <a href="#" style="color: gray;">@Html.DisplayFor(modelItem => item.Carrera.Nombre)</a>
                </li>
            </ul>
        }
    </div>
</div>
<script>
        $(document).ready(function () {
            var titulo = $('#titulo').text("Cursos");
            console.log(titulo);
        });
</script>

Utalca/Utalca/Views/Home/Index.cshtml
@model Utalca.ControlAsistencia.Curso
@{
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
    ViewBag.Title = "Ingresar - Facultad de Ingeniería";
}


<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Ingresar</h3>
            </div>
            <div class="panel-body">
                <form action="/Curso" class="form-signin" data-abide="true" method="post">
                    <div class="form-group">
                        <label for="Email">Correo Electrónico</label>
                        <input id="Email" name="Email" class="form-control" placeholder="Su correo electrónico" />
                    </div>
                    <div class="form-group">
                        <label for="Password">Contraseña</label>
                        <input id="Password" name="Password" class="form-control" placeholder="Su contraseña" type="password" />
                        <a class="pull-right small">Olvid&#243; su contrase&#241;a?</a>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> Recuérdame
                        </label>
                    </div>
                    <div class="padd-t-20">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Ingresar</button>
                    </div>
                </form>
            </div>
            <div class="panel-footer">Aún no tienes cuenta?  <a href="#" data-toggle="modal" data-target="#RegistroModal"> Regístrate</a> aquí!</div>
        </div>
    </div>
</div>

Utalca/Utalca/Views/Profesor/Detalles.cshtml
@model Utalca.Models.Profesor
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Académico - Facultad Ingeniería";
}

<div class="row">
    <div class="col-md-3">
        <div class="gallery-box">
            <img style="width: 200px;" src="/Content/img/@Model.Foto" />
        </div>
        <h4 id="nombre" hidden="true" class="card-title">@Model.Nombre    @Model.Apellido</h4>
        <hr style="clear:both" />
        <h4 class="card-title">Sitio Web</h4>
        <p style="font-size: 16px;">
            @Model.SitioWeb
        </p><br /> 
       
    </div>
    <div class="col-md-9 " >
        <div class="panel panel-default" style="background-color:#f9f9f9">
            <div class="panel-body">
                <h3>Biografía</h3>
                <hr style="clear:both" />
                <p>@Model.Biografia</p>
                <h3>Mis Cursos</h3>
                <hr style="clear:both" />
                @foreach (var curso in @Model.Cursos)
                {
                    <p><a  href="@Url.Action("Detalles", "Curso", new { id = curso.ID })" >@curso.Nombre</a></p>
                }
                
            </div>
        </div> 
    </div>
</div>
   

<script>
    $(document).ready(function () {
        var nombre = $('#nombre').text();
        $('#titulo').text(nombre);
     });
</script>

Utalca/Utalca/Views/Profesor/Index.cshtml
@model IEnumerable<Utalca.Models.Profesor>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Académicos - Facultad Ingeniería";
}






<div class="row">
    <div class="card-deck-wrapper">
        @foreach (var profesor in Model)
        {
            <div class="col-sm-6 col-md-4">
                <div class="card">
                    <img class="card-img-top" src="/Content/img/@profesor.Foto" alt="Académico" style="height: 200px;">
                    <div class="card-block">
                        <h4 class="card-title">@profesor.Nombre @profesor.Apellido</h4>
                        <a href="@Url.Action("Detalles", "Profesor", new { id = profesor.ID })" class="btn btn-primary" role="button">Perfil</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<script>
        $(document).ready(function () {
            var titulo = $('#titulo').text("Académicos");
            console.log(titulo);
        });
</script>

Utalca/Utalca/Views/Profesor/ProfesorNoEncontrado.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "ProfesorNoEncontrado";
}
<div class="jumbotron">
    <p><a class="btn btn-lg btn-primary" href="@Url.Action("Index", "Profesor")">Volver a profesores</a></p>
    <a href="@Url.Action("Index", "Curso")" class="btn btn-primary" role="button">Mis Cursos</a>
</div>
<script>
        $(document).ready(function () {
            var titulo = $('h3').text("Académico No Encontrado");
            console.log(titulo);
        });
</script>

Utalca/Utalca/Views/Shared/_Errores.cshtml
@{
    var ultimoMensaje = Utalca.Utils.MensajesUI.ObtieneUltimoError();
}

@if (!string.IsNullOrEmpty(ultimoMensaje))
{
    <div id="ErroresModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Encontramos algunos errores</h4>
                </div>
                <div class="modal-body">
                    <p>@ultimoMensaje</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
}

Utalca/Utalca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet"/>
    <link rel="icon" type="image/ico" href="/Content/img/utalca.ico" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>

    @Html.Partial("_Menu")
    <div class="jumbotron" style="background-color:#f9f9f9">
        <div class="container">
            <h3 id="titulo">Titulo Defecto</h3>
        </div>
    </div>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Facultad de Ingeniería de la Universidad de Talca - 2016</p>
        </footer>
    </div>
    
    @Html.Partial("_Errores")

    <script>
        $(document).ready(function () {
            if ($('#ErroresModal').length > 0)
            {
                $("#ErroresModal").modal('show')
            }

        });
    </script>
    
</body>
</html>

Utalca/Utalca/Views/Shared/_LayoutIndex.cshtml
<!DOCTYPE html>
<html>
<head>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title </title>
        <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link rel="icon" type="image/ico" href="/Content/img/utalca.ico" />
        <script src="~/Scripts/modernizr-2.6.2.js"></script>
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
    </head>
</head>
<body>
    <header id="header">
        <!-- //top-header -->
        <!-- navbar -->
        <div class="navbar navbar-v1 padd-tb-30 yamm stay-top nav" role="navigation">
            <div class="container">
                <div class="navbar-header">

                    <a class="navbar-brand" href="/">
                        <img src="/Content/img/logo.jpg" style="width: 100%; max-width: 300px; min-width: 200px" alt="logo" />
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <div class="pull-right hidden-md hidden-sm hidden-xs" style="text-align:right; padding-bottom: 10px">
                        <a href="http://www.utalca.cl" target="_blank">
                            <img src="/Content/img/logoUtalcaNegro.png" style="height: 25px" alt="logo" />
                        </a>
                    </div>
                    <br style="clear: both" />
                </div><!--/.nav-collapse -->
            </div><!-- ./container -->
        </div>
        <!-- //navbar -->
    </header>
    <!-- /header -->
    
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <div class="jumbotron">
        <footer>
            <p>&copy; @DateTime.Now.Year - Control de Asistecncia</p>
            <p>Facultad de Ingeniería de la Universidad de Talca - 2016</p>
        </footer>
    </div>
    @Html.Partial("_Errores")

    <script>
        $(document).ready(function () {
            if ($('#ErroresModal').length > 0)
            {
                $("#ErroresModal").modal('show')
            }

        });
    </script>
    
</body>
</html>

Utalca/Utalca/Views/Shared/_Menu.cshtml
<header id="header">
    <!-- navbar -->
    <div class="navbar navbar-v1 padd-tb-30 yamm stay-top nav" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img src="/Content/img/logo.jpg" style="width: 100%; max-width: 300px; min-width: 200px" alt="logo" />
                </a>
                <!--<a class="navbar-brand" href="#"><span>c</span>larity</a>-->
            </div>
                <div class="navbar-collapse collapse">
                    <div class="pull-right hidden-md hidden-sm hidden-xs" style="text-align:right; padding-bottom: 10px">
                        <a href="http://www.utalca.cl" target="_blank"><img src="/Content/img/logoUtalcaNegro.png" style="height: 25px" alt="logo" /></a>
                    </div>
                    <br style="clear: both" />
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/Profesor">Académicos</a></li>
                        <li><a href="/">Salir</a></li>
                    </ul>

                </div><!--/.nav-collapse -->
            </div><!-- ./container -->
    </div>
    <!-- //navbar -->

</header>
<!-- /header -->